#!/usr/bin/env bash

set -eu
[ "${TRACE:-false}" = 'true' ] && set -x

cd "$1"

yes y | pnpm install --offline --force --frozen-lockfile
NODE_ENV=production pnpm run --recursive build
NODE_ENV=production pnpm run build:assets

# Trim down the dependencies to only those for production
find . -path '*/node_modules/*' -delete
yes y | pnpm install --offline --force --prod --frozen-lockfile
