#!/usr/bin/env bash

set -euo pipefail
[ "${TRACE:-false}" = 'true' ] && set -x

find . -path '*/node_modules/*' -delete
find . -name 'node_modules' -delete
find ./packages -maxdepth 4 -name built -type d -exec rm -rf {} +
rm -rf \
    built \
	packages/backend/assets/instance.css \
    packages/backend-rs/target \
    packages/megalodon/lib
