#!/usr/bin/env bash

set -euo pipefail
[ "${TRACE:-false}" = 'true' ] && set -x

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

SOURCE_DIR="$1"

aptly repo create firefish

for deb_file in "$SOURCE_DIR"/*.deb; do
    aptly repo add firefish "$deb_file"
done


