#!/usr/bin/env bash

set -euo pipefail
[ "${TRACE:-false}" = 'true' ] && set -x

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

GITHUB_TAG_NAME="$1"

make version
[ "v$(cat "$PROJECT_DIR/VERSION.txt")" = "$GITHUB_TAG_NAME" ]
