#!/usr/bin/env bash

set -euo pipefail
[ "${TRACE:-false}" = 'true' ] && set -x

DEB_FILE_PATH="$1"

make version

DPKG_DEB_VERSION="$(dpkg-deb --show "$DEB_FILE_PATH" | awk '{print $2}')"
[ "$DPKG_DEB_VERSION" = "$(cat VERSION.txt)" ]
