#!/usr/bin/env bash

set -euo pipefail
[ "${TRACE:-false}" = 'true' ] && set -x

GITHUB_TAG_NAME="$1"
DEB_FILE_PATH="$2"

DPKG_DEB_VERSION="$(dpkg-deb --show "$DEB_FILE_PATH" | awk '{print $2}')"
[ "v$DPKG_DEB_VERSION" = "$GITHUB_TAG_NAME" ]
