#!/usr/bin/env bash

set -euo pipefail
[ "${TRACE:-false}" = 'true' ] && set -x

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

mkdir -p "$1"
TARGET_DIR="$(cd "$1" && pwd)"

cp -r "$PROJECT_DIR/files/"* "$TARGET_DIR/"
cp -r "$PROJECT_DIR/common/tasks" "$TARGET_DIR/common_tasks"
cp -r "$PROJECT_DIR/common/assets" "$TARGET_DIR/common_assets"
