#!/usr/bin/env bash

set -euo pipefail
[ "${TRACE:-false}" = 'true' ] && set -x

apt-get update -y
apt-get install -y \
    wget \
    dh-make \
    make \
    rsync \

wget -q -O- 'https://deb.nodesource.com/gpgkey/nodesource.gpg.key' \
    | gpg --dearmor | tee /usr/share/keyrings/nodesource.gpg >/dev/null
tee /etc/apt/sources.list.d/nodesource.list <<EOS
deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x ${DISTRO} main
EOS

apt-get update -y
apt-get install -y nodejs

wget -O/tmp/rustup-init.bash https://sh.rustup.rs
bash /tmp/rustup-init.bash -y \
  --no-modify-path \
  --profile minimal \
  --default-toolchain stable
source "$HOME/.cargo/env"
rustup self update
rustup update

corepack enable
corepack prepare --activate pnpm@latest

cargo install cargo-about
