#!/usr/bin/env bash

set -euo pipefail
[ "${TRACE:-false}" = 'true' ] && set -x

for i in `seq 1 130`; do
    if curl --fail -sL http://localhost:3000; then
        break
    fi
    sleep 5
done

HOME_HTML="$(curl --fail -sL http://localhost:3000)"
if ! echo "$HOME_HTML" | grep 'Thank you for using Firefish!' >/dev/null; then
    echo 'Failed to find "Thank you for using Firefish!" in home page'
    echo "$HOME_HTML"
    exit 1
fi
