#!/usr/bin/env bash

set -euo pipefail
[ "${TRACE:-false}" = 'true' ] && set -x

GITHUB_TAG_NAME="$1"
DEB_FILE_PATH="$2"
PKG_VERSION_DEB="$(echo "$GITHUB_TAG_NAME" | sed -E 's/^v(.+)$/\1/')"

dpkg-deb --show "$DEB_FILE_PATH" | grep -E "^firefish\s+${PKG_VERSION_DEB}$"
