#!/usr/bin/env bash

set -euo pipefail
[ "${TRACE:-false}" = 'true' ] && set -x

cd "$1"

pnpm i --force --frozen-lockfile
pnpm run build

# Trim down the dependencies to only those for production
rm -rf node_modules
pnpm i --force --prod --frozen-lockfile

# Generate the license file
(cd packages/backend-rs && cargo about init)
tee packages/backend-rs/about.toml <<EOS
accepted = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "MPL-2.0",
    "NOASSERTION",
    "OpenSSL",
    "Unicode-DFS-2016",
]
EOS
(cd packages/backend-rs && cargo about generate about.hbs > cargo-licenses.html)
