#!/usr/bin/env bash

set -euo pipefail
[ "${TRACE:-false}" = 'true' ] && set -x

mkdir -p "$1"
LIVE_DIR="$(cd "$1" && pwd)"

rsync --recursive --relative --links \
    custom \
    .node-version \
    .npmrc \
    animated.svg \
    package.json \
    patrons.json \
    pnpm-lock.yaml \
    pnpm-workspace.yaml \
    release.json \
    title.svg \
    CHANGELOG.md \
    COPYING \
    LICENSE \
    README.md \
    RELEASE_NOTES.md \
    SECURITY.md \
    built \
    node_modules \
    packages/backend/package.json \
    packages/backend/ormconfig.js \
    packages/backend/assets \
    packages/backend/migration \
    packages/backend/built \
    packages/backend/node_modules \
    packages/backend/native-utils/package.json \
    packages/backend/native-utils/Cargo.toml \
    packages/backend/native-utils/Cargo.lock \
    packages/backend/native-utils/cargo-licenses.html \
    packages/backend/native-utils/npm \
    packages/backend/native-utils/built \
    packages/backend/native-utils/node_modules \
    packages/firefish-js/package.json \
    packages/firefish-js/LICENSE \
    packages/firefish-js/README.md \
    packages/firefish-js/built \
    packages/firefish-js/node_modules \
    packages/client/package.json \
    packages/client/node_modules \
    packages/sw/package.json \
    packages/sw/node_modules \
    packages/megalodon/package.json \
    packages/megalodon/node_modules \
    packages/megalodon/lib \
    "${LIVE_DIR}/"
