include envs/params.make

PKG_VERSION_FIREFISH?=20240430
PKG_VERSION_DEB?=$(PKG_VERSION_FIREFISH)-d202405040001+release

FIREFISH_SOURCE_GIT_REPO?=https://firefish.dev/firefish/firefish
FIREFISH_SOURCE_GIT_COMMIT_REF?=v$(PKG_VERSION_FIREFISH)

