#!/usr/bin/env bash

set -euo pipefail
[ "${TRACE:-false}" = 'true' ] && set -x

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

DEST_DIR="$PROJECT_DIR/dest"

rm -rf "$DEST_DIR"
mkdir -p "$DEST_DIR"

"$PROJECT_DIR/repo/scripts/build-repo-in-docker"
cp -r "$PROJECT_DIR/repo/dest"/* "$DEST_DIR/"

cp -r "$PROJECT_DIR/docs" "$DEST_DIR/docs"

cp -r "$PROJECT_DIR/public"/* "$DEST_DIR/"
