#!/usr/bin/env bash

set -euo pipefail
[ "${TRACE:-false}" = 'true' ] && set -x

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

mkdir -p "$1"
TARGET_DIR="$(cd "$1" && pwd)"

SOURCE_TARBALL="$2"

tar -xf "$SOURCE_TARBALL" --strip-components 1 -C "$TARGET_DIR"

DEBIAN_DIR="$TARGET_DIR/debian"
mkdir -p "$DEBIAN_DIR"
cp -r "$PROJECT_DIR/debian/files/"* "$DEBIAN_DIR/"
