#!/usr/bin/env bash

set -euo pipefail
[ "${TRACE:-false}" = 'true' ] && set -x

TEMP_DIR="$(mktemp -d)"
trap 'rm -rf -- "$TEMP_DIR"' EXIT

apt-get update -y
DEBIAN_FRONTEND=noninteractive apt-get install -y \
    wget \
    make \

wget -O "$TEMP_DIR/nodejs-setup.bash" https://deb.nodesource.com/setup_20.x
bash "$TEMP_DIR/nodejs-setup.bash"

apt-get update -y

wget -O "$TEMP_DIR/rustup-init.bash" https://sh.rustup.rs
bash "$TEMP_DIR/rustup-init.bash" -y \
  --no-modify-path \
  --profile minimal \
  --default-toolchain stable
source "$HOME/.cargo/env"
rustup self update
rustup update
