#!/usr/bin/env bash

set -euo pipefail
[ "${TRACE:-false}" = 'true' ] && set -x

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "${SCRIPT_DIR}/env.bash"

TARGET_ARCH="${TARGET_ARCH:-"$(dpkg-architecture -qDEB_HOST_ARCH)"}"

TEMPLATE_DIR="${WORK_DIR}/firefish"

mkdir -p "${INSTALL_DIR}"
cp -r "$TEMPLATE_DIR" "${INSTALL_DIR}/firefish"

cd "${SOURCE_DIR}"

LIVEDIR="${INSTALL_DIR}/firefish/var/lib/firefish/live"
mkdir -p "${LIVEDIR}"

mv \
    custom \
    .node-version \
    .npmrc \
    animated.svg \
    package.json \
    patrons.json \
    pnpm-lock.yaml \
    pnpm-workspace.yaml \
    release.json \
    title.svg \
    built \
    node_modules \
    CHANGELOG.md \
    COPYING \
    LICENSE \
    README.md \
    RELEASE_NOTES.md \
    SECURITY.md \
    "${LIVEDIR}/"

mkdir -p "${LIVEDIR}/packages/backend"
mv \
    packages/backend/package.json \
    packages/backend/ormconfig.js \
    packages/backend/assets \
    packages/backend/built \
    packages/backend/migration \
    packages/backend/node_modules \
    "${LIVEDIR}/packages/backend/"

mkdir -p "${LIVEDIR}/packages/backend/native-utils"
mv \
    packages/backend/native-utils/package.json \
    packages/backend/native-utils/Cargo.toml \
    packages/backend/native-utils/Cargo.lock \
    packages/backend/native-utils/cargo-licenses.html \
    packages/backend/native-utils/npm \
    packages/backend/native-utils/built \
    packages/backend/native-utils/node_modules \
    "${LIVEDIR}/packages/backend/native-utils/"

mkdir -p "${LIVEDIR}/packages/firefish-js"
mv \
    packages/firefish-js/package.json \
    packages/firefish-js/LICENSE \
    packages/firefish-js/CHANGELOG.md \
    packages/firefish-js/README.md \
    packages/firefish-js/built \
    packages/firefish-js/node_modules \
    "${LIVEDIR}/packages/firefish-js/"

mkdir -p "${LIVEDIR}/packages/client"
mv \
    packages/client/package.json \
    packages/client/node_modules \
    "${LIVEDIR}/packages/client/"

mkdir -p "${LIVEDIR}/packages/sw"
mv \
    packages/sw/package.json \
    packages/sw/node_modules \
    "${LIVEDIR}/packages/sw/"

mkdir -p "${LIVEDIR}/packages/megalodon"
mv \
    packages/megalodon/package.json \
    packages/megalodon/node_modules \
    packages/megalodon/lib \
    "${LIVEDIR}/packages/megalodon/"

m4 \
    "-D__ARCH__=${TARGET_ARCH}" \
    "-D__VERSION__=${PKG_VERSION}" \
    "-D__NODE_MAJOR_VERSION__=${NODE_MAJOR_VERSION}" \
    "${WORK_DIR}/control.m4" \
    > "${INSTALL_DIR}/firefish/DEBIAN/control"

mkdir -p "${DEST_DIR}"
cd "${DEST_DIR}"

# Ubuntu use zstd by default and Debian failed to unpack zstd archive.
dpkg-deb -Zgzip --build "${INSTALL_DIR}/firefish/" .
