#!/usr/bin/env bash

set -euo pipefail
[ "${TRACE:-false}" = 'true' ] && set -x

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "${SCRIPT_DIR}/env.bash"

mkdir -p "${SOURCE_DIR}"
mkdir -p "${INSTALL_DIR}"

apt-get update -y

apt-get install -y \
    git \
    build-essential \
    debhelper \
    devscripts \
    lsb-release \
    wget

wget -O/tmp/rustup-init.bash https://sh.rustup.rs
bash /tmp/rustup-init.bash -y \
  --profile minimal \
  --default-toolchain stable
source "$HOME/.cargo/env"
cargo install cargo-about

DEB_BUILD_GNU_TYPE="$(dpkg-architecture -qDEB_BUILD_GNU_TYPE)"
DEB_HOST_MULTIARCH="$(dpkg-architecture -qDEB_HOST_MULTIARCH)"
DISTRO="$(lsb_release -c -s 2>/dev/null)"

git clone \
    --branch "$CALCKEY_SOURCE_VERSION" \
    --depth 1 \
    "$CALCKEY_SOURCE_GIT_REPO" "${SOURCE_DIR}"

wget -q -O- 'https://deb.nodesource.com/gpgkey/nodesource.gpg.key' \
    | gpg --dearmor | tee /usr/share/keyrings/nodesource.gpg >/dev/null
tee /etc/apt/sources.list.d/nodesource.list <<EOS
deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x ${DISTRO} main
EOS

apt-get update -y

# Install build dependencies
apt-get install -y \
    nodejs

corepack enable
corepack prepare pnpm@latest --activate

cd "${SOURCE_DIR}"

pnpm i --frozen-lockfile
pnpm run build

# Trim down the dependencies to only those for production
pnpm i --prod --frozen-lockfile

(cd packages/backend/native-utils && cargo about init)
tee packages/backend/native-utils/about.toml <<EOS
accepted = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "MPL-2.0",
    "NOASSERTION",
    "OpenSSL",
    "Unicode-DFS-2016",
]
EOS
(cd packages/backend/native-utils && cargo about generate about.hbs > cargo-licenses.html)

rm -rf \
    ~/.local \
    packages/backend/native-utils/target
