#!/usr/bin/env bash

set -euo pipefail
[ "${TRACE:-false}" = 'true' ] && set -x

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "${SCRIPT_DIR}/env.bash"

source "$HOME/.cargo/env"
cargo install cargo-about

DEB_BUILD_GNU_TYPE="$(dpkg-architecture -qDEB_BUILD_GNU_TYPE)"
DEB_HOST_MULTIARCH="$(dpkg-architecture -qDEB_HOST_MULTIARCH)"

git clone \
    --branch "$FIREFISH_SOURCE_VERSION" \
    --depth 1 \
    "$FIREFISH_SOURCE_GIT_REPO" "${SOURCE_DIR}"

cd "${SOURCE_DIR}"

pnpm i --frozen-lockfile
pnpm run build

# Trim down the dependencies to only those for production
pnpm i --prod --frozen-lockfile

(cd packages/backend/native-utils && cargo about init)
tee packages/backend/native-utils/about.toml <<EOS
accepted = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "MPL-2.0",
    "NOASSERTION",
    "OpenSSL",
    "Unicode-DFS-2016",
]
EOS
(cd packages/backend/native-utils && cargo about generate about.hbs > cargo-licenses.html)
