#!/usr/bin/env bash

set -euo pipefail
[ "${TRACE:-false}" = 'true' ] && set -x

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

if [[ ${GITHUB_REF_NAME:-} =~ ^v[0-9.]+-(d[0-9]+-(release|rc|beta|alpha))$ ]]; then
    PKG_VERSION_DEB="${BASH_REMATCH[1]}"
else
    PKG_VERSION_DEB="d$(date +%Y%m%d%H%M%S)-alpha"
fi

cat <<EOS
PKG_VERSION_DEB=${PKG_VERSION_DEB}
EOS
