#!/usr/bin/env bash

set -euo pipefail
[ "${TRACE:-false}" = 'true' ] && set -x

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "${SCRIPT_DIR}/env.bash"

apt install -y "${INSTALL_DIR}/"firefish_*.deb

/usr/bin/firefish-migrate || echo
/usr/bin/firefish-start || echo
