#!/usr/bin/env bash

set -euo pipefail
[ "${TRACE:-false}" = 'true' ] && set -x

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "${SCRIPT_DIR}/env.bash"

apt-get update -y

apt-get install -y \
    wget \
    gpg

wget -q -O- 'https://deb.nodesource.com/gpgkey/nodesource.gpg.key' \
    | gpg --dearmor | tee /usr/share/keyrings/nodesource.gpg >/dev/null
tee /etc/apt/sources.list.d/nodesource.list <<EOS
deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_${NODE_MAJOR_VERSION}.x ${DISTRO} main
EOS

apt-get update -y

apt-get install -y \
    nodejs

apt install -y "${DEST_DIR}/"firefish_*.deb
