#!/usr/bin/env bash

set -euo pipefail
[ "${TRACE:-false}" = 'true' ] && set -x

sleep 60

for i in `seq 1 120`; do
    if curl --fail -sL http://localhost:3000; then
        break
    fi
    sleep 5
done

curl --fail -sL http://localhost:3000 | grep 'Thank you for using Firefish!' >/dev/null
